### PR TITLE
Add excluding paths functionality

### PR DESCRIPTION
**Pull request by Kitton**

### CODE REVIEW

**Comment by kaorism** [comment]
thanks

**Comment by Kitton** [comment]
@kaorism can you please publish the changes to https://hex.pm/packages/credo_envvar ?

**Comment by kaorism** [comment]
done! thanks @Kitton

**Comment by Kitton** [comment]
@kaorism sorry for bothering you again, but looks like the version pushed to hex doesn't have any changes, but only version update to `0.1.3`. Can you check it?

**Comment by kaorism** [comment]
sorry, my mistake. please try again

**Pull request merged**
